name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir arquivos
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v2
